# Generated by Django 3.0.4 on 2020-03-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SangTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('sang', models.CharField(max_length=30)),
                ('su', models.IntegerField()),
                ('dan', models.IntegerField()),
            ],
        ),
    ]
